package com.virginvoyages.recommendations.calendar;

import java.util.List;

import javax.validation.constraints.NotNull;

import org.joda.time.LocalDate;
import org.springframework.hateoas.ExposesResourceFor;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import com.virginvoyages.recommendations.content.ContentRecommendation;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;

@RestController
@Api(value = "CalendarRecommendation", tags = "CalendarRecommendation", description = "Calendar Recommendation")
@Slf4j
@RequiredArgsConstructor
@ExposesResourceFor(ContentRecommendation.class)
public class CalenderRecommendationController {

	@ApiOperation(value = "", notes = "To request calendar recommendations from the recommendation engine.", response = CalendarRecommendations.class, tags = {
			"Calendar Recommendation", })
	@ApiResponses(value = {
			@ApiResponse(code = 200, message = "Successful response", response = CalendarRecommendations.class) })
	@RequestMapping(value = "/calenderRecommendation", method = RequestMethod.POST)
	public ResponseEntity<CalendarRecommendations> calenderRecommendationPost(
			@NotNull @ApiParam(value = "The system making the request, use the sailor ID + system to leverage the x-ref to find the data lake identifier", required = true) @RequestParam(value = "requestSource", required = true) String requestSource,
			@NotNull @ApiParam(value = "The END system identifier for the sailor", required = true) @RequestParam(value = "sailorID", required = true) String sailorID,
			@NotNull @ApiParam(value = "this is the reservation ID pointing to data in the RES (Seaware) system", required = true) @RequestParam(value = "reservationIDs", required = true) List<String> reservationIDs,
			@NotNull @ApiParam(value = "The place identifier for the recommendation. This will an array of places consisting of PlaceID and PlaceName separated by '|' (pipe)- e.g. 01|Spa, 02|Cabin, etc this is a defined enumerate that is constant between channels (Spa on the ship is Spa on the web)", required = true) @RequestParam(value = "place", required = true) List<String> place,
			@NotNull @ApiParam(value = "the max number of recommendations per category that are desired", required = true) @RequestParam(value = "qtyPerPlace", required = true) List<Integer> qtyPerPlace,
			@NotNull @ApiParam(value = "the startDate of time for which curated news will be computed", required = true) @RequestParam(value = "startDate", required = true) LocalDate startDate,
			@NotNull @ApiParam(value = "the endDate of time for which curated news will be computed", required = true) @RequestParam(value = "endDate", required = true) LocalDate endDate,
			@NotNull @ApiParam(value = "Channel identifier - Mobile, Web, Ship Screen, Voice, Call Centre - what is the end requesting medium this is an enumerate", required = true, allowableValues = "MOBILE, WEB, SHIP_SCREEN, VOICE, CALL_CENTRE") @RequestParam(value = "channel", required = true) String channel,
			@ApiParam(value = "an identifier generated by the calling application for its own purposes") @RequestHeader(value = "X-Correlation-ID", required = false) String xCorrelationID,
			@ApiParam(value = "Application identifier of client") @RequestHeader(value = "X-VV-Client-ID", required = false) String xVVClientID,
			@ApiParam(value = "Additional sailors accompanying the primary Sailor ID") @RequestParam(value = "groupSailors", required = false) List<String> groupSailors,
			@ApiParam(value = "A variable tuple envelop of additional meta-data that is not used at this stage but may be of use in future (e.g. cookies, URIs, etc) this is used for machine learning in the future, not the individual request. The format of meta-data tuple would be pipe separated key value pair.  e.g [\"URL\"| \"www.example.com\", ...]") @RequestParam(value = "metaData", required = false) List<String> metaData) {
		
		log.debug("Entering calenderRecommendationPost");
		return new ResponseEntity<CalendarRecommendations>(HttpStatus.OK);
	}

}
