package com.virginvoyages.recommendations.response;

import javax.validation.constraints.NotNull;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.hateoas.ExposesResourceFor;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import com.virginvoyages.api.MockRecommendationAPI;
import com.virginvoyages.recommendations.assembly.RecommendationsResponseAssembly;
import com.virginvoyages.recommendations.model.Recommendation;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;

@RestController
@Api(value = "Recommendation", tags = "Recommendation", description = "Recommendation Response")
@Slf4j
@RequiredArgsConstructor
@ExposesResourceFor(Recommendation.class)
public class RecommendationResponseController {
	
	@Autowired
	private MockRecommendationAPI mockAPI;
	
	@Autowired
	private RecommendationsResponseAssembly recommendationsResponseAssembly;

	@ApiOperation(value = "", notes = "To update the exising recommendation with feedback based on the customer's selected option", response = Void.class, tags = {
			"Recommendation Response", })
	@ApiResponses(value = { @ApiResponse(code = 200, message = "Successful response", response = Void.class) })
	@RequestMapping(value = "/recommendationResponse", method = RequestMethod.PUT)

	public ResponseEntity<Void> recommendationResponsePut(
			@NotNull @ApiParam(value = "the unique key associated with each recommendation when it is issued", required = true) @RequestParam(value = "nbxUniqueKey", required = true) Integer nbxUniqueKey,
			@NotNull @ApiParam(value = "from the recommendation that was issued, what the sailor selected", required = true) @RequestParam(value = "sailorSelection", required = true) String sailorSelection,
			@ApiParam(value = "an identifier generated by the calling application for its own purposes") @RequestHeader(value = "X-Correlation-ID", required = false) String xCorrelationID,
			@ApiParam(value = "Application identifier of client") @RequestHeader(value = "X-VV-Client-ID", required = false) String xVVClientID,
			@ApiParam(value = "this will be a set of codes to be defined", allowableValues = "DEFAULT_NOT_SELECTED_, SELECTED, NOT_SHOWN, REJECTED") @RequestParam(value = "selectionSentiment", required = false) String selectionSentiment) {

		log.debug("Entering recommendationResponsePut");
		recommendationsResponseAssembly.addRecommendationResponse(nbxUniqueKey, sailorSelection, selectionSentiment);
		return new ResponseEntity<Void>(HttpStatus.OK);
	}
}
