kind: Service
apiVersion: v1
metadata:
  name: sailor-api-service
  labels:
    name: sailor-api-service
    visualize: "true"
spec:
    type: NodePort
    ports:
     - name: http
       nodePort: 31432
       port: 80
       targetPort: 8432
    selector:
      name: sailor-api-service
