
/**
 * Flyway Migration Script.
 * Engine: MySQL
 * Version: 0.2
 * Description:Initial Master data. 
 */

INSERT INTO REFERENCE_SOURCE VALUES (uuid(), 'VXP', 0);
INSERT INTO REFERENCE_SOURCE VALUES (uuid(), 'SALESFORCE', 0);
INSERT INTO REFERENCE_SOURCE VALUES (uuid(), 'SEAWARE', 0);
INSERT INTO REFERENCE_SOURCE VALUES (uuid(), 'ANALYTICS', 0);
INSERT INTO REFERENCE_SOURCE VALUES (uuid(), 'SPMS', 0);
INSERT INTO REFERENCE_SOURCE VALUES (uuid(), 'FACEBOOK', 0);
INSERT INTO REFERENCE_SOURCE VALUES (uuid(), 'TWITTER', 0);
INSERT INTO REFERENCE_SOURCE VALUES (uuid(), 'INSTAGRAM', 0);


INSERT INTO REFERENCE_TYPE VALUES (uuid(), (select REFERENCE_SOURCE_ID from REFERENCE_SOURCE where REFERENCE_SOURCE = 'VXP'), 'WebProfile');
INSERT INTO REFERENCE_TYPE VALUES (uuid(), (select REFERENCE_SOURCE_ID from REFERENCE_SOURCE where REFERENCE_SOURCE = 'SALESFORCE'), 'Person');
INSERT INTO REFERENCE_TYPE VALUES (uuid(), (select REFERENCE_SOURCE_ID from REFERENCE_SOURCE where REFERENCE_SOURCE = 'SEAWARE'), 'Client');
INSERT INTO REFERENCE_TYPE VALUES (uuid(), (select REFERENCE_SOURCE_ID from REFERENCE_SOURCE where REFERENCE_SOURCE = 'SEAWARE'), 'Guest');
INSERT INTO REFERENCE_TYPE VALUES (uuid(), (select REFERENCE_SOURCE_ID from REFERENCE_SOURCE where REFERENCE_SOURCE = 'ANALYTICS'), 'Anonymous');
INSERT INTO REFERENCE_TYPE VALUES (uuid(), (select REFERENCE_SOURCE_ID from REFERENCE_SOURCE where REFERENCE_SOURCE = 'ANALYTICS'), 'C-360');
INSERT INTO REFERENCE_TYPE VALUES (uuid(), (select REFERENCE_SOURCE_ID from REFERENCE_SOURCE where REFERENCE_SOURCE = 'SPMS'), 'Wearable');
INSERT INTO REFERENCE_TYPE VALUES (uuid(), (select REFERENCE_SOURCE_ID from REFERENCE_SOURCE where REFERENCE_SOURCE = 'FACEBOOK'), 'Facebook');
INSERT INTO REFERENCE_TYPE VALUES (uuid(), (select REFERENCE_SOURCE_ID from REFERENCE_SOURCE where REFERENCE_SOURCE = 'TWITTER'), 'Twitter');
INSERT INTO REFERENCE_TYPE VALUES (uuid(), (select REFERENCE_SOURCE_ID from REFERENCE_SOURCE where REFERENCE_SOURCE = 'INSTAGRAM'), 'Instagram');

COMMIT;