apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sailor-api-service
  labels:
    name: sailor-api-service
    version: latest
    visualize: "true"
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: sailor-api-service
        version: latest
        visualize: "true"
    spec:
          containers:
          - name: sailor-api
            image: murtazacg/sailor-api:0.0.1
            imagePullPolicy: "Always"
            resources:
              limits:
                memory: 700Mi
            env:
            - name: LOG_LOCATION
              valueFrom:
                configMapKeyRef:
                  name: integration-api-configmap
                  key: LOG_LOCATION
            - name: APPLICATION_PROPERTIES_PATH
              valueFrom:
                configMapKeyRef:
                  name: integration-api-configmap
                  key: SAILOR_API_SERVICE_PROPERTIES_PATH
            - name: SERVICE_PROPERTIES_PATH
              valueFrom:
                configMapKeyRef:
                  name: integration-api-configmap
                  key: SAILOR_API_SERVICE_PROPERTIES_PATH
            ports:
             - containerPort: 8432
            volumeMounts:
            - name: log-mount
              mountPath: /var/log/applogs/Logs
            - name: sailor-api-properties
              mountPath: /etc/config/sailor-api/
          volumes:
          - name: log-mount
            hostPath:
              path: /var/log/applogs/sailor-api/
          - name: sailor-api-properties
            configMap:
              name: sailor-api-configmap
